### ISSUE TITLE
Integrity constraint violation: 1048 Column 'created' cannot be null

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/node_clone#14]
I'm getting the following error:

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created' cannot be null`

Steps to reproduce:

1. Spin up a new site
2. Enable "Sample Animal Content" module
3. Add and enable "Node Clone" module
4. Go to `/admin/config/content/clone` and change "Method to use when cloning a node" to "Save as a new node then edit."
5. Go to `/animals/saltwater-crocodile` and try to clone node
6. ![image](https://github.com/backdrop-contrib/node_clone/assets/3144571/0ea93432-efe4-420d-a45c-7a4b3a6c2f47)
7. After confirmation, click "CLONE" and you should get this fatal error.

![image](https://github.com/backdrop-contrib/node_clone/assets/3144571/e7a92d9d-52dc-4731-8632-870fd6f21cd0)

**Comment by olafgrabienski** [comment]
I'm testing the module on a demo site. While I'm able to clone _Pages_ and _Posts_, I can confirm the issue with the _Animal_ content type. There are two detailed error messages in DBlog:

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created' cannot be null: INSERT INTO {taxonomy_index} (`nid`, `tid`, `sticky`, `created`) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array ( [:db_insert_placeholder_0] => 15 [:db_insert_placeholder_1] => 1 [:db_insert_placeholder_2] => 0 [:db_insert_placeholder_3] => ) in taxonomy_build_node_index() (line 2101 of /var/lib/tugboat/backdrop/core/modules/taxonomy/taxonomy.module).

> EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created' cannot be null in NodeStorageController->save() (line 512 of /var/lib/tugboat/backdrop/core/modules/node/node.entity.inc).

**Comment by Sharif8190** [comment]
@robertgarrigos I have create a pull request for the issue #14 
It is working for me and I am working on this issue for Triplo. Hope you review this PR.

**Comment by argiepiano** [comment]
This is a strange problem. I see that the code uses the PHP command `clone` of the original node object. All saved nodes MUST have a `created` value, so my guess is that the problem is happening somewhere else  before reaching this point. This PR will most likely mask another problem.

**Comment by robertgarrigos** [comment]
It is not really an error happening somewhere else before reaching this point. It is more just the way it works. The module uses the _clone_node_prepare function differently when prepopulating than when saving directly as a new node and edit. In the former case, the form recreates the `$node->created` property, while the latter doesn't.

I think it is just easier to change the _clone_node_prepare function than trying to fix this different use of the function somewhere else. However, I would do it differently because the proposed pr would leave the cloned node with the same created date as the original node, which would be a different functionality than before.

Thus, instead of: 

```
$node->created = isset($node->created) ? $node->created : REQUEST_TIME;
```
I would do:

```
$node->created = REQUEST_TIME;
```
